baseurl: /
languageCode: en-us, ru
title: Мой новый крутой сайт
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Блог
      url: /blog/
      weight: 1
    - name: Эконометрика в R
      url: /post/
      weight: 2
    - name: О сайте
      url: /about/
      weight: 3
    - name: GitHub
      url: https://github.com/ETymch/Econometrics_2023
      weight: 4
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  favicon: favicon.ico
  description: A website built through Hugo and blogdown.
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: logo
    height: 110
    url: logo.png
    width: 110
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
